### ISSUE TITLE
Servicenow connector is failing with Java socket closed exception

### ISSUE THREAD

**Issue by kuntabala** [IBM/kafka-connect-servicenow#5]
Jun 16 10:33:09  connect-distributed: org.apache.kafka.connect.errors.ConnectException: An error occurred while initializing the ServiceNow Client.
Jun 16 10:33:09  connect-distributed: at com.ibm.ingestion.connect.servicenow.source.ServiceNowTableAPISourceTask.start(ServiceNowTableAPISourceTask.java:60)
Jun 16 10:33:09  connect-distributed: at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:219)
Jun 16 10:33:09  connect-distributed: at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:185)
Jun 16 10:33:09  connect-distributed: at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:235)
Jun 16 10:33:09  connect-distributed: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
Jun 16 10:33:09  connect-distributed: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
Jun 16 10:33:09  connect-distributed: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
Jun 16 10:33:09  connect-distributed: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
Jun 16 10:33:09  connect-distributed: at java.lang.Thread.run(Thread.java:748)
Jun 16 10:33:09  connect-distributed: Caused by: java.io.InterruptedIOException: timeout
Jun 16 10:33:09  connect-distributed: at okhttp3.internal.connection.Transmitter.timeoutExit(Transmitter.java:109)
Jun 16 10:33:09  connect-distributed: at okhttp3.internal.connection.Transmitter.maybeReleaseConnection(Transmitter.java:302)
Jun 16 10:33:09  connect-distributed: at okhttp3.internal.connection.Transmitter.noMoreExchanges(Transmitter.java:267)
Jun 16 10:33:09  connect-distributed: at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
Jun 16 10:33:09  connect-distributed: at okhttp3.RealCall.execute(RealCall.java:81)
Jun 16 10:33:09  connect-distributed: at com.ibm.ingestion.http.ServiceNowTableApiClient.getAuthenticationToken(ServiceNowTableApiClient.java:346)
Jun 16 10:33:09  connect-distributed: at com.ibm.ingestion.http.ServiceNowTableApiClient.refreshAuthenticationToken(ServiceNowTableApiClient.java:380)
Jun 16 10:33:09  connect-distributed: at com.ibm.ingestion.http.ServiceNowTableApiClient.init(ServiceNowTableApiClient.java:83)
Jun 16 10:33:09  connect-distributed: at com.ibm.ingestion.connect.servicenow.source.ServiceNowTableAPISourceTask.start(ServiceNowTableAPISourceTask.java:57)
Jun 16 10:33:09  connect-distributed: ... 8 more
Jun 16 10:33:09  connect-distributed: Caused by: java.net.SocketException: Socket closed
Jun 16 10:33:09  connect-distributed: at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:354)
Jun 16 10:33:09  connect-distributed: at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
Jun 16 10:33:09  connect-distributed: at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
Jun 16 10:33:09  connect-distributed: at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
Jun 16 10:33:09  connect-distributed: at java.net.Socket.connect(Socket.java:607)
Jun 16 10:33:09  connect-distributed: at okhttp3.internal.platform.Platform.connectSocket(Platform.java:130)
Jun 16 10:33:09  connect-distributed: at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:263)
Jun 16 10:33:09  connect-distributed: at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:183)
Jun 16 10:33:09  connect-distributed: at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:224)
Jun 16 10:33:09  connect-distributed: at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:107)
Jun 16 10:33:09  connect-distributed: at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:87)
Jun 16 10:33:09  connect-distributed: at okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:169)
Jun 16 10:33:09  connect-distributed: at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41)
Jun 16 10:33:09  connect-distributed: at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
Jun 16 10:33:09  connect-distributed: at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
Jun 16 10:33:09  connect-distributed: at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
Jun 16 10:33:09  connect-distributed: at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)

**Comment by mike-treadway** [comment]
Hi, can you post your connector config (minus the credentials)? A socket closed exception directly from ServiceNow is unlikely, but certainly possible. I would suspect one of the following:

- A mismatch of HTTP/HTTPS protocol.
- A proxy server or firewall in-between your connector and ServiceNow

**Comment by kuntabala** [comment]
It is the same configuration parameters that we are using as it was mentioned.

{
    "name": "milz-servicenow-connector",
    "config": {
        "servicenow.client.base.uri": xxxxxx,
        "servicenow.client.oauth.path": "xxxx",
        "servicenow.client.oauth.clientid": "xxxxx",
        "servicenow.client.oauth.clientsecret": "xxxxx",
        "servicenow.client.oauth.username": "xxxxx",
        "servicenow.client.oauth.userpassword": "xxxxx",
        "table.whitelist": "xxx",
        "table.whitelist.case.name": "xxxxxx",
        "table.whitelist.case.timestamp.field.name": "xxxx",
        "table.whitelist.case.identifier.field.name": "xxx",
        "table.whitelist.case.fields": "xxxx",
        "table.whitelist.case.partition.type": "xxxx",
        "table.whitelist.changerequest.name": "xxx",
        "table.whitelist.changerequest.timestamp.field.name": "xxx",
        "table.whitelist.changerequest.identifier.field.name": "xxx",
        "table.whitelist.changerequest.partition.type": "xxx",
        "table.whitelist.changerequest.partition.fields": "xxxx",
        "topic.prefix": "test.milz.servicenowconnector1",
        "timestamp.initial.query.hours.ago": 720,
        "tasks.max": 1,
        "connector.class": "com.ibm.ingestion.connect.servicenow.ServiceNowSourceConnector"
    }
}

**Comment by mike-treadway** [comment]
I'm not seeing how this is a problem with the connector, but more likely a network issue. My suggestion is to get a shell into the server (or container) that is running the connector and verify that you have network connectivity to the endpoint set in your `servicenow.client.base.uri` configuration setting.

**Comment by kuntabala** [comment]
What we hear from the servicenow team is , we need to enable proxy to reach the endpoint URI. Is there anyway we can enable the proxy on the connector level.?

**Comment by mike-treadway** [comment]
I'll need to take a closer look, but have you tried setting common OS level environment variables like `http_proxy`? I need to validate if the http client used by this connector respect those values. But until I do, give that a try.

https://www.golinuxcloud.com/set-up-proxy-http-proxy-environment-variable/

**Comment by kuntabala** [comment]
Hi Mike,

I tried updating the env variable and then i tried doing wget and curl to servicenow URI, network connection works  from my virtual machine. But i am getting the same error socket closed exception when i rerun the connector.

**Comment by mike-treadway** [comment]
Hi, the HTTP client used in this connector is [okhttp](https://square.github.io/okhttp/). The documentation [here](https://square.github.io/okhttp/3.x/okhttp/) says it will use system level JVM proxy settings by default. Those settings are defined [here](https://docs.oracle.com/javase/7/docs/api/java/net/doc-files/net-properties.html).

Can you try adding `http.proxyHost` and `http.proxyPort` JVM settings? You should be able to add these as options when starting KafkaConnect by passing in `-Dhttp.proxyHost=your_proxy -Dhttp.proxyPort=8080` on the command line.

**Comment by kuntabala** [comment]
Hi Mike,

These parameters worked fine. Now we are able to make connection with servicenow.

But we are facing a different issue now. Our schema registry service is mTLS enabled. So when the client is reading the data from servicenow and sending the data to our Kafka topic, we are getting deserialization issue. Can you please let me know if this connector supports mTLS?
If yes, what properties should we enable in the connector like ssl.keystore? ssl.truststore???

**Comment by kuntabala** [comment]
Jun 24 15:22:28 connect-distributed: [task-thread-milz-servicenow-connector-0] ERROR io.confluent.kafka.schemaregistry.client.rest.RestService - Failed to send HTTP request to endpoint: https://xxxxxxxxx:port/subjects/test.milz.servicenowconnector1.case-value/versions
Jun 24 15:22:28 connect-distributed: javax.net.ssl.SSLHandshakeException: Received fatal alert: bad_certificate
Jun 24 15:22:28 connect-distributed: at sun.security.ssl.Alert.createSSLException(Alert.java:131)
Jun 24 15:22:28 connect-distributed: at sun.security.ssl.Alert.createSSLException(Alert.java:117)
Jun 24 15:22:28 connect-distributed: at sun.security.ssl.TransportContext.fatal(TransportContext.java:311)
Jun 24 15:22:28 connect-distributed: at sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:293)
Jun 24 15:22:28 connect-distributed: at sun.security.ssl.TransportContext.dispatch(TransportContext.java:185)
Jun 24 15:22:28 connect-distributed: at sun.security.ssl.SSLTransport.decode(SSLTransport.java:152)
Jun 24 15:22:28 connect-distributed: at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1383)
Jun 24 15:22:28 connect-distributed: at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1291)
Jun 24 15:22:28 connect-distributed: at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:435)
Jun 24 15:22:28 connect-distributed: at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
Jun 24 15:22:28 connect-distributed: at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:197)
Jun 24 15:22:28 connect-distributed: at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1340)
Jun 24 15:22:28 connect-distributed: at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1315)
Jun 24 15:22:28 connect-distributed: at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:264)
Jun 24 15:22:28 connect-distributed: at io.confluent.kafka.schemaregistry.client.rest.RestService.sendHttpRequest(RestService.java:263)
Jun 24 15:22:28 connect-distributed: at io.confluent.kafka.schemaregistry.client.rest.RestService.httpRequest(RestService.java:352)
Jun 24 15:22:28 connect-distributed: at io.confluent.kafka.schemaregistry.client.rest.RestService.registerSchema(RestService.java:495)
Jun 24 15:22:28 connect-distributed: at io.confluent.kafka.schemaregistry.client.rest.RestService.registerSchema(RestService.java:486)
Jun 24 15:22:28 connect-distributed: at io.confluent.kafka.schemaregistry.client.rest.RestService.registerSchema(RestService.java:459)
Jun 24 15:22:28 connect-distributed: at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.registerAndGetId(CachedSchemaRegistryClient.java:214)
Jun 24 15:22:28 connect-distributed: at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.register(CachedSchemaRegistryClient.java:276)
Jun 24 15:22:28 connect-distributed: at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.register(CachedSchemaRegistryClient.java:252)
Jun 24 15:22:28 connect-distributed: at io.confluent.kafka.serializers.AbstractKafkaAvroSerializer.serializeImpl(AbstractKafkaAvroSerializer.java:75)
Jun 24 15:22:28 connect-distributed: at io.confluent.connect.avro.AvroConverter$Serializer.serialize(AvroConverter.java:143)
Jun 24 15:22:28 connect-distributed: at io.confluent.connect.avro.AvroConverter.fromConnectData(AvroConverter.java:84)
Jun 24 15:22:28 connect-distributed: at org.apache.kafka.connect.storage.Converter.fromConnectData(Converter.java:63)
Jun 24 15:22:28 connect-distributed: at org.apache.kafka.connect.runtime.WorkerSourceTask.lambda$convertTransformedRecord$2(WorkerSourceTask.java:301)
Jun 24 15:22:28 connect-distributed: at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndRetry(RetryWithToleranceOperator.java:128)

**Comment by kuntabala** [comment]
Hi @mike-treadway  

Can you please help me or suggest me what configuration parameters i need to add so that the client where the connector is running can authenticate with the schema registry server?

**Comment by mmillies** [comment]
Hi @kuntabala ,

Have you tried reviewing the Schema Registry's documentation on integration with Kafka Connect? Is it not working?

https://docs.confluent.io/platform/current/schema-registry/connect.html

This connector's implementation does not do any special schema registration calls.

That being said, I'd suggest you review that documentation and try to configure Kafka Connect itself to use the schema registry and see if that solves your problem. (This could simply be adding Kafka Connect level configuration values to the connector's configuration definition.)

** I'd also suggest we close this issue as the original goal was achieved and we've moved onto a different issue.

CC: @mike-treadway
